### ISSUE TITLE
Bundle ID is not being reused successfully when `xtool dev` is used

### ISSUE THREAD

**Issue by marcusziade** [xtool-org/xtool#87]
## Description

When I use `xtool dev` the first time with a fresh bundle ID, everything works, but any subsequent `xtool dev` commands, using the same bundle ID, give this error:

<details>
  <summary>Click me</summary>

```
marcus@arch:~/Dev/swift/Hello$ xtool dev
Planning...
[1/1] Planning build
Building for debugging...
[4/4] Linking Hello-App
Build of product 'Hello-App' complete! (0.47s)
Waiting for device to be connected...
Installing to device: Marcus iPhone  (udid: obfuscated)

[Unpacking app] 100%
[Logging in]   0%
[Preparing device] 100%
[Provisioning]  66%
Error: Unexpected response, expected status code: created, response: conflict(DeveloperAPI.Operations.BundleIdsCreateInstance.Output.Conflict(body: DeveloperAPI.Operations.BundleIdsCreateInstance.Output.Conflict.Body.json(DeveloperAPI.Components.Schemas.ErrorResponse(errors: Optional([DeveloperAPI.Components.Schemas.ErrorResponse.ErrorsPayloadPayload(id: Optional("obfuscated"), status: "409", code: "ENTITY_ERROR.ATTRIBUTE.INVALID", title: "An attribute in the provided entity has invalid value", detail: "An App ID with Identifier \'XTL-A5EBDAB5.com.marcusziade.HelloXTool5\' is not available. Please enter a different string.", source: nil, links: nil, meta: nil)])))))
```
  
</details>

Every time I build, I have to change the bundle ID, or I get that error about the string already being used.

## Environment

Host OS: Arch Linux

iOS device version:
18.5, 18.2, 15.8.3

Swift version:
6.1

SDK version:
marcus@arch:~$ swift sdk --version
Swift Package Manager - Swift 6.1.0

**Comment by kabiroberai** [comment]
Could you please share the output of `xtool ds identifiers`? Feel free to redact details.

**Comment by marcusziade** [comment]
<details>
  <summary>Click me</summary>

```
marcus@arch:~$ xtool ds identifiers
- id: 
  name: XC com marcusziade master-of-step
  identifier: com.marcusziade.master-of-step
  platform: UNIVERSAL
  seedId: 
- id: 
  name: sforesight created by Xcode Cloud
  identifier: com.marcusziade.sforesight
  platform: UNIVERSAL
  seedId: 
- id: 
  name: oikotieremastered created by Xcode Cloud
  identifier: com.marcusziade.oikotie-remastered
  platform: UNIVERSAL
  seedId: 
- id: 
  name: XC com marcusziade ste
  identifier: com.marcusziade.ste
  platform: UNIVERSAL
  seedId: 
- id: 
  name: masterofuniverse created by Xcode Cloud
  identifier: com.marcusziade.master-of-universe
  platform: UNIVERSAL
  seedId: 
- id: 
  name: XC com marcusziade master-of-steps-own
  identifier: com.marcusziade.master-of-steps-own
  platform: UNIVERSAL
  seedId: 
- id: 
  name: Master of Inventory Develop
  identifier: com.marcusziade.inventory.develop
  platform: UNIVERSAL
  seedId: 
- id: 
  name: XC Wildcard
  identifier: *
  platform: UNIVERSAL
  seedId: 
- id: 
  name: legendstracker created by Xcode Cloud
  identifier: com.marcusziade.legendstracker
  platform: UNIVERSAL
  seedId: 
- id: 
  name: XC com marcusziade siri-shortcuts-raywenderlich
  identifier: com.marcusziade.siri-shortcuts-raywenderlich
  platform: UNIVERSAL
  seedId: 
- id: 
  name: solarbeam created by Xcode Cloud
  identifier: com.marcusziade.solarbeam
  platform: UNIVERSAL
  seedId: 
- id: 
  name: psywave created by Xcode Cloud
  identifier: com.marcusziade.psywave
  platform: UNIVERSAL
  seedId: 
- id: 
  name: XC com marcusziade steps
  identifier: com.marcusziade.steps
  platform: UNIVERSAL
  seedId: 
- id: 
  name: masterofmemes created by Xcode Cloud
  identifier: com.marcusziade.masterofmemes
  platform: UNIVERSAL
  seedId: 
- id: 
  name: Apex created by Xcode Cloud
  identifier: com.marcusziade.Apex
  platform: UNIVERSAL
  seedId: 
- id: 
  name: SongLink created by Xcode Cloud
  identifier: com.marcusziade.quicksonglink
  platform: UNIVERSAL
  seedId: 
- id: 
  name: Apex created by Xcode Cloud
  identifier: com.marcusziade.apex-stats-tracker
  platform: UNIVERSAL
  seedId: 
- id: 
  name: DreamEater created by Xcode Cloud
  identifier: com.marcusziade.DreamEater
  platform: UNIVERSAL
  seedId: 
- id: 
  name: endure created by Xcode Cloud
  identifier: com.marcusziade.endure
  platform: UNIVERSAL
  seedId: 
- id: 
  name: XC com marcusziade Momentum
  identifier: com.marcusziade.Momentum
  platform: UNIVERSAL
  seedId: 
```
  
</details>
